const BASE="https://3asq.online";
function abs(u){if(!u)return;try{u=new URL(String(u).trim(),BASE);return/^https?:$/i.test(u.protocol)?u.href:undefined}catch{return}}
function path(u){try{const x=new URL(String(u).trim(),BASE);return x.pathname.replace(/^\/+|\/+$/g,"")+(x.search||"")}catch{return""}}
async function doc(p){const r=await harbor.http(BASE+p,{responseType:"text"});return r.ok?harbor.parseHtml(r.body):null}
function text(r,s){for(const x of s){const e=r.querySelector(x),t=e?(e.text()||"").trim():"";if(t)return t}return""}
function meta(d,n){const w=n.map(x=>x.toLowerCase());for(const m of d.querySelectorAll("meta")){const k=((m.attr("property")||m.attr("name")||"")+"").toLowerCase();if(w.includes(k))return(m.attr("content")||"").trim()}return""}
function img(i){return i&&abs(i.attr("data-src")||i.attr("data-lazy-src")||i.attr("data-original")||i.attr("data-lazy")||i.attr("src"))}
function cover(d){const m=meta(d,["og:image","twitter:image"]);if(m)return abs(m);for(const s of [".summary_image img",".summary-image img",".post-thumbnail img"]){const u=img(d.querySelector(s));if(u)return u}}
function isChapterLink(h){return /\/manga\/[^/]+\/\d+(?:\.\d+)?\/?(?:\?.*)?$/i.test(h)||/chapter[\s._-]*\d+/i.test(h)}
function summaries(d){const o=[],seen=new Set();for(const s of [".page-item-detail",".bsx",".manga-item","article"]){for(const c of d.querySelectorAll(s)){let a=null;for(const x of c.querySelectorAll("a")){const h=x.attr("href")||"";if(/\/manga\//i.test(h)&&!isChapterLink(h)){a=x;break}}if(!a)continue;const id=path(a.attr("href")||""),title=(a.attr("title")||a.text()||text(c,["h2","h3",".title"])||"").trim();if(id&&title&&!seen.has(id)){seen.add(id);o.push({id,title,cover:img(c.querySelector("img")||a.querySelector("img"))})}}}return o}
function paths(kind,p,q,t){const e=encodeURIComponent(q||""),g=t?encodeURIComponent(t):"";if(kind==="popular")return g?[`/manga-genre/${g}/?m_orderby=views&page=${p}`,`/genre/${g}/?m_orderby=views&page=${p}`]:[`/manga/?m_orderby=views&page=${p}`,`/manga/page/${p}/?m_orderby=views`];return g?[`/manga-genre/${g}/?s=${e}&post_type=wp-manga&page=${p}`,`/genre/${g}/?s=${e}&post_type=wp-manga&page=${p}`]:[`/manga/?s=${e}&post_type=wp-manga&page=${p}`,`/?s=${e}&post_type=wp-manga&page=${p}`]}
function chnum(t,h){const s=`${t||""} ${h||""}`;for(const r of [/chapter[\s._-]*(\d+(?:\.\d+)?)/i,/\bch[\s._-]*(\d+(?:\.\d+)?)/i,/\/([0-9]+(?:\.[0-9]+)?)\/?(?:\?|$)/]){const m=s.match(r);if(m)return m[1]}return null}
function chaptersFromDoc(d){const o=[],seen=new Set();const add=a=>{const h=a.attr("href")||"",id=path(h),t=(a.text()||a.attr("title")||"").trim(),n=chnum(t,h);if(!id||!n||seen.has(id)||!isChapterLink(h))return;seen.add(id);o.push({id,chapter:n,title:t||`الفصل ${n}`,volume:a.attr("data-volume")||a.attr("data-vol")||null,pages:0,language:"en"})};for(const s of [".wp-manga-chapter a",".wp-manga-chapters a",".chapter-list a",".version-chap a",".listing-chapters_wrap a",".chapter-item a"]){for(const a of d.querySelectorAll(s))add(a)}for(const a of d.querySelectorAll('a[href*="/manga/"]'))add(a);o.sort((a,b)=>parseFloat(b.chapter)-parseFloat(a.chapter));return o}
function rangeFromDoc(d){const nums=[];for(const a of d.querySelectorAll('a[href*="/manga/"]')){const n=chnum(a.text(),a.attr("href")||"");if(n)nums.push(parseFloat(n))}for(const s of [".wp-manga-chapter", ".wp-manga-chapters", ".summary-content", ".post-content_item"]){const e=d.querySelector(s);if(!e)continue;const t=e.text()||"";const ms=t.match(/\b\d+(?:\.\d+)?\b/g);if(ms)for(const x of ms)nums.push(parseFloat(x))}const f=nums.filter(Number.isFinite);if(!f.length)return null;return{min:Math.floor(Math.min(...f)),max:Math.ceil(Math.max(...f))}}
async function checkChapter(mangaId,n){const p=`/${String(mangaId).replace(/^\/+|\/+$/g,"")}/${n}/`;const r=await harbor.http(BASE+p,{responseType:"text"});if(!r.ok||!r.body)return null;const d=harbor.parseHtml(r.body);const title=text(d,["h1.entry-title","h1",".c-breadcrumb-wrapper .item:last-child"])||`الفصل ${n}`;const body=d.text()||"";if(!new RegExp(`(?:الفصل|chapter)\\s*0*${String(n).replace(/\\./g,"\\.")}\\b|\\b${String(n).replace(/\\./g,"\\.")}\\b`,"i").test(body+title))return null;return{id:path(p),chapter:String(n),title,volume:null,pages:0,language:"en"}}
async function numericChapters(mangaId,d){const r=rangeFromDoc(d);if(!r)return[];const found=[];const seen=new Set();const chunk=20;for(let start=r.min;start<=r.max;start+=chunk){const jobs=[];for(let n=start;n<=Math.min(r.max,start+chunk-1);n++)jobs.push(checkChapter(mangaId,n));const rows=await Promise.all(jobs);for(const c of rows)if(c&&!seen.has(c.id)){seen.add(c.id);found.push(c)}}found.sort((a,b)=>parseFloat(b.chapter)-parseFloat(a.chapter));return found}
async function pageUrls(id){const p=String(id).replace(/^\/+/,""),d=await doc("/"+p),o=[],seen=new Set();if(d)for(const s of [".reading-content img","#readerarea img",".page-break img",".entry-content .page-break img",".wp-manga-chapter-img img",".manga-chapter img"]){for(const i of d.querySelectorAll(s)){const u=img(i);if(u&&!seen.has(u)){seen.add(u);o.push(u)}}}return o}
const plugin={id:"3asq-online",name:"3asq.online",async popular(offset,tagId){for(const p of paths("popular",Math.floor(offset/48)+1,"",tagId)){const d=await doc(p),x=d&&summaries(d);if(x&&x.length)return x}return[]},async search(q,offset,tagId){for(const p of paths("search",Math.floor(offset/48)+1,q,tagId)){const d=await doc(p),x=d&&summaries(d);if(x&&x.length)return x}return[]},async detail(id){const clean=String(id).replace(/^\/+/,""),d=await doc("/"+clean);if(!d)return null;const y=text(d,[".year",".release-year",".summary-content.year"]).match(/\b(19\d{2}|20\d{2})\b/);const cs=chaptersFromDoc(d);return{id,title:text(d,[".post-title h1",".summary-title h1","h1.entry-title","h1"])||meta(d,["og:title"])||id,altTitle:text(d,[".alternative",".alt-title"])||undefined,cover:cover(d),year:y?Number(y[1]):undefined,status:text(d,[".post-status .summary-content",".summary-content.status"])||undefined,description:meta(d,["og:description","description"])||text(d,[".summary__content",".summary_content",".summary-content",".description-summary"]),lastChapter:cs.length?cs[0].title:undefined,author:text(d,[".author-content",".author",".summary-content.author"])||undefined}},async chapters(id){const clean=String(id).replace(/^\/+/,""),d=await doc("/"+clean);if(!d)return[];const direct=chaptersFromDoc(d);const generated=await numericChapters(clean,d);const all=[...direct,...generated],seen=new Set(),out=[];for(const c of all)if(!seen.has(c.id)){seen.add(c.id);out.push(c)}out.sort((a,b)=>parseFloat(b.chapter)-parseFloat(a.chapter));return out},async pageUrls(id){return pageUrls(id)},async tags(){const o=[],seen=new Set();for(const p of ["/manga-genre/","/genre/","/genres/","/"]){const d=await doc(p);if(!d)continue;for(const a of d.querySelectorAll('a[href*="/manga-genre/"],a[href*="/genre/"],a[href*="/genres/"]')){const id=path(a.attr("href")||"").replace(/^(manga-genre|genre|genres)\//i,"").replace(/^\/+|\/+$/g,""),name=(a.text()||"").trim();if(id&&name&&!seen.has(id)){seen.add(id);o.push({id,name,group:"Genre"})}}}return o}};harbor.register(plugin);