const BASE="https://3asq.online";
function abs(u){if(!u)return;try{const x=new URL(String(u).trim(),BASE);return/^https?:$/i.test(x.protocol)?x.href:undefined}catch{return}}
function path(u){try{const x=new URL(String(u).trim(),BASE);return x.pathname.replace(/^\/+|\/+$/g,"")+(x.search||"")}catch{return""}}
async function doc(p){const r=await harbor.http(BASE+p,{responseType:"text"});return r&&r.ok?harbor.parseHtml(r.body):null}
function text(r,s){for(const x of s){const e=r.querySelector(x),t=e?(e.text()||"").trim():"";if(t)return t}return""}
function meta(d,n){const w=n.map(x=>x.toLowerCase());for(const m of d.querySelectorAll("meta")){const k=((m.attr("property")||m.attr("name")||"")+"").toLowerCase();if(w.includes(k))return(m.attr("content")||"").trim()}return""}
function img(i){return i&&abs(i.attr("data-src")||i.attr("data-lazy-src")||i.attr("data-original")||i.attr("src"))}
function cover(d){const m=meta(d,["og:image","twitter:image"]);if(m)return abs(m);for(const s of [".summary_image img",".summary-image img",".post-thumbnail img"]){const u=img(d.querySelector(s));if(u)return u}}
function chnum(t,h){const s=`${t||""} ${h||""}`;for(const r of [/chapter[\s._-]*(\d+(?:\.\d+)?)/i,/الفصل[\s._-]*(\d+(?:\.\d+)?)/i,/\bch[\s._-]*(\d+(?:\.\d+)?)/i,/\/([0-9]+(?:\.[0-9]+)?)\/?(?:\?|$)/]){const m=s.match(r);if(m)return m[1]}return null}
function isChapterLink(h){return /\/manga\/[^/]+\/\d+(?:\.\d+)?\/?(?:\?.*)?$/i.test(h)||/(?:chapter|الفصل|ch)[\s._-]*\d+(?:\.\d+)?/i.test(h)}
function addChapter(o,seen,a){const h=a.attr("href")||"",id=path(h),t=(a.text()||a.attr("title")||"").trim(),n=chnum(t,h);if(!id||!n||!isChapterLink(h)||seen.has(id))return;seen.add(id);o.push({id,chapter:n,title:t||`الفصل ${n}`,volume:a.attr("data-volume")||a.attr("data-vol")||null,pages:0,language:"ar"})}
function chaptersFromDoc(d){const o=[],seen=new Set();for(const s of [".wp-manga-chapter a",".wp-manga-chapters a",".chapter-list a",".version-chap a",".listing-chapters_wrap a",".chapter-item a",".c-tabs-item__content a",".row-content-chapter a"]){for(const a of d.querySelectorAll(s))addChapter(o,seen,a)}for(const a of d.querySelectorAll('a[href*="/manga/"]'))addChapter(o,seen,a);o.sort((a,b)=>parseFloat(b.chapter)-parseFloat(a.chapter));return o}
function nextPage(d){for(const a of d.querySelectorAll("a")){const h=a.attr("href")||"",t=(a.text()||"").trim().toLowerCase(),rel=(a.attr("rel")||"").toLowerCase();if(rel.includes("next")||/^(next|التالي|›|»|>|older)$/i.test(t))return path(h);if(/page[=\/-]\d+/i.test(h)&&/next|التالي|›|»/i.test(t))return path(h)}return null}
async function collectChapterPages(slug,first){const out=[],seen=new Set(),visited=new Set();let p=first||`/manga/${slug}/`,count=0;while(p&&count<80&&!visited.has(p)){visited.add(p);const d=await doc(p);if(!d)break;for(const s of [".wp-manga-chapter a",".wp-manga-chapters a",".chapter-list a",".version-chap a",".listing-chapters_wrap a",".chapter-item a",".c-tabs-item__content a",".row-content-chapter a"]){for(const a of d.querySelectorAll(s))addChapter(out,seen,a)}for(const a of d.querySelectorAll('a[href*="/manga/"]'))addChapter(out,seen,a);p=nextPage(d);count++}out.sort((a,b)=>parseFloat(b.chapter)-parseFloat(a.chapter));return out}
function summaries(d){const o=[],seen=new Set();for(const s of [".page-item-detail",".bsx",".manga-item","article"]){for(const c of d.querySelectorAll(s)){let a=null;for(const x of c.querySelectorAll("a")){const h=x.attr("href")||"";if(/\/manga\//i.test(h)&&!isChapterLink(h)){a=x;break}}if(!a)continue;const id=path(a.attr("href")||""),title=(a.attr("title")||a.text()||text(c,["h2","h3",".title"])||"").trim();if(id&&title&&!seen.has(id)){seen.add(id);o.push({id,title,cover:img(c.querySelector("img")||a.querySelector("img"))})}}}return o}
function paths(kind,p,q,t){const e=encodeURIComponent(q||""),g=t?encodeURIComponent(t):"";if(kind==="popular")return g?[`/manga-genre/${g}/?m_orderby=views&page=${p}`,`/genre/${g}/?m_orderby=views&page=${p}`]:[`/manga/?m_orderby=views&page=${p}`,`/manga/page/${p}/?m_orderby=views`];return g?[`/manga-genre/${g}/?s=${e}&post_type=wp-manga&page=${p}`,`/genre/${g}/?s=${e}&post_type=wp-manga&page=${p}`]:[`/manga/?s=${e}&post_type=wp-manga&page=${p}`,`/?s=${e}&post_type=wp-manga&page=${p}`]}
async function pageUrls(id){const d=await doc("/"+String(id).replace(/^\/+/,"")),o=[],seen=new Set();if(d)for(const s of [".reading-content img","#readerarea img",".page-break img",".entry-content .page-break img",".wp-manga-chapter-img img",".manga-chapter img"]){for(const i of d.querySelectorAll(s)){const u=img(i);if(u&&!seen.has(u)){seen.add(u);o.push(u)}}}return o}
const plugin={id:"3asq-online",name:"3asq.online",version:"1.0.20",async popular(offset,tagId){for(const p of paths("popular",Math.floor(offset/48)+1,"",tagId)){const d=await doc(p),x=d&&summaries(d);if(x&&x.length)return x}return[]},async search(q,offset,tagId){for(const p of paths("search",Math.floor(offset/48)+1,q,tagId)){const d=await doc(p),x=d&&summaries(d);if(x&&x.length)return x}return[]},async detail(id){const clean=String(id).replace(/^\/+/,""),d=await doc("/"+clean);if(!d)return null;const y=text(d,[".year",".release-year",".summary-content.year"]).match(/\b(19\d{2}|20\d{2})\b/);const all=await collectChapterPages(clean.split("/")[0],"/"+clean);return{id,title:text(d,[".post-title h1",".summary-title h1","h1.entry-title","h1"])||meta(d,["og:title"])||id,altTitle:text(d,[".alternative",".alt-title"])||undefined,cover:cover(d),year:y?Number(y[1]):undefined,status:text(d,[".post-status .summary-content",".summary-content.status"])||undefined,description:meta(d,["og:description","description"])||text(d,[".summary__content",".summary_content",".summary-content",".description-summary"]),lastChapter:all.length?all[0].title:undefined,author:text(d,[".author-content",".author",".summary-content.author"])||undefined}},async chapters(id){const clean=String(id).replace(/^\/+/,"");return collectChapterPages(clean.split("/")[0],"/"+clean)},async pageUrls(id){return pageUrls(id)},async tags(){const o=[],seen=new Set();for(const p of ["/manga-genre/","/genre/","/genres/","/"]){const d=await doc(p);if(!d)continue;for(const a of d.querySelectorAll('a[href*="/manga-genre/"],a[href*="/genre/"],a[href*="/genres/"]')){const id=path(a.attr("href")||"").replace(/^(manga-genre|genre|genres)\//i,"").replace(/^\/+|\/+$/g,""),name=(a.text()||"").trim();if(id&&name&&!seen.has(id)){seen.add(id);o.push({id,name,group:"Genre"})}}}return o}};harbor.register(plugin);